plugins:
  - jekyll-nagymaros
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
remote_theme: piazzai/cvless
